services:
  ark-asa:
    image: azixus/ark-ascended-docker:latest
    container_name: ark-asa-server
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./ark_data:/opt/arkserver
      - ./ark_backup:/var/backups/asa-server
      - steam_data:/opt/steamcmd
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      # Uncomment to expose RCON
      # - "${RCON_PORT}:${RCON_PORT}/tcp"
    stop_grace_period: 45s
    deploy:
      resources:
        limits:
          memory: 16g
    memswap_limit: 16g

volumes:
  steam_data:
